# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# run `pre-commit install` to set up the git hook scripts
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
