version: "3"

services:
  app:
    container_name: kam
    image: "ghcr.io/kamailio/${KAMA_IMG}"
    entrypoint: /etc/kamailio/sh/kam/restart.sh
    depends_on:
      - db
    environment:
      - KAMA_CFG=${KAMA_CFG}
      - KAMA_LISTEN=${KAMA_LISTEN}
    volumes:
      - type: bind
        source: $PWD
        target: /etc/kamailio/
    network_mode: host

  db:
    container_name: pg
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: $PWD/sh/pg
        target: /docker-entrypoint-initdb.d/
    network_mode: host
